name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
          - platform: windows
            os: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Install Linux dependencies
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake clang ninja-build libgtk-3-dev

      - name: Build
        run: flutter build ${{ matrix.platform }}

      - name: Create Linux archive
        if: matrix.platform == 'linux'
        run: tar -czf xunity_ai_translator-${{ matrix.platform }}-${{ github.ref_name }}.tar.gz -C build/${{ matrix.platform }}/x64/release/bundle/ .

      - name: Create Windows archive
        if: matrix.platform == 'windows'
        shell: pwsh
        run: |
          cd build\${{ matrix.platform }}\x64\runner\Release\
          Compress-Archive -Path * -DestinationPath $env:GITHUB_WORKSPACE\xunity_ai_translator-${{ matrix.platform }}-${{ github.ref_name }}.zip

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            xunity_ai_translator-${{ matrix.platform }}-${{ github.ref_name }}.*
          draft: false
          prerelease: false
