name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
          - platform: windows
            os: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Install Linux dependencies
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake clang ninja-build libgtk-3-dev

      - name: Build
        run: flutter build ${{ matrix.platform }}

      - name: Create archive
        run: |
          if [ "${{ matrix.platform }}" = "windows" ]; then
            cd build/${{ matrix.platform }}/x64/release/bundle/
            zip -r xunity_ai_translator-${{ matrix.platform }}-${{ github.ref_name }}.zip .
            mv xunity_ai_translator-${{ matrix.platform }}-${{ github.ref_name }}.zip $GITHUB_WORKSPACE/
          else
            tar -czf xunity_ai_translator-${{ matrix.platform }}-${{ github.ref_name }}.tar.gz -C build/${{ matrix.platform }}/x64/release/bundle/ .
          fi

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            xunity_ai_translator-${{ matrix.platform }}-${{ github.ref_name }}.*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
